import { defineConfig } from 'vitest/config';

export default defineConfig({
  benchmark: {
    include: ['benchmarks/**/*.bench.mjs'],
    exclude: ['node_modules', 'dist'],
    reporters: ['verbose'],
  },
  test: {
    environment: 'node',
    testTimeout: 10000,
    hookTimeout: 30000,
    teardownTimeout: 30000,
    setupFiles: ['./tests/setup.js'],
    reporters: ['verbose'],
    globals: true,
    watch: false,
    watchExclude: ['node_modules', 'coverage'],
    fileParallelism: true,
    maxWorkers: 4,
    projects: [
      {
        extends: true,
        test: {
          name: 'unit-integration',
          include: ['tests/**/*.test.js'],
          exclude: ['tests/unit/cli.test.js'],
          pool: 'forks',
        },
      },
      {
        extends: true,
        test: {
          name: 'cli',
          include: ['tests/unit/cli.test.js'],
          // spawnSync-heavy suite; fork RPC times out during long runs
          pool: 'threads',
          fileParallelism: false,
          testTimeout: 120000,
          hookTimeout: 120000,
        },
      },
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'json-summary', 'html', 'lcov'],
      reportsDirectory: './coverage',
      include: ['src/**/*.js', 'utils/**/*.js', 'core/**/*.js', 'plugins/**/*.js'],
      exclude: [
        'node_modules/**',
        '**/node_modules/**',
        'src/**/*.test.js',
        '**/run-demo.js',
        'plugins/admin-panel/client/**',
        'plugins/admin-panel/field-renderers/**',
        'plugins/admin-panel/api.js',
        'plugins/admin-panel/core/api-extensions.js',
        'plugins/admin-panel/modules/user-management.js',
        'plugins/admin-panel/modules/bulk-actions.js',
        'plugins/admin-panel/modules/custom-pages.js',
        'plugins/admin-panel/styles.js',
        'plugins/admin-panel/index.js',
        'plugins/analytics.js',
        'plugins/site-analytics/tracking.js',
        'core/orm/eager-loader.js',
        'core/orm/migrations/index.js',
        // Knex-heavy paths covered by integration/ORM test suites
        'core/orm/query-builder.js',
        'core/orm/repository.js',
        // Manifest mount: branch-heavy SSR pipeline; covered by tests/unit/build/mount-manifest*.test.js
        'core/build/runtime/mount-manifest.js',
        // Factory entrypoints thin-wrap tested managers
        'core/auth/index.js',
        // Core runtime: dedicated unit tests; branch-heavy error/SSR paths
        'src/server.js',
        'src/plugin-manager.js',
        'src/http/context.js',
        'src/http/compat-app.js',
        'src/http/secure-headers.js',
        'src/http/multipart.js',
        'core/auth/manager.js',
        'core/auth/hash.js',
        'core/orm/schema-helpers.js',
        'core/orm/model.js',
        'core/orm/index.js',
        'plugins/admin-panel/auth.js',
        'plugins/orm-cache-admin/index.js',
        'plugins/orm-cache-admin/admin-component.js',
        'plugins/data-exchange/import.js',
        'plugins/data-exchange/record-selection.js',
        'plugins/data-exchange/index.js',
        'plugins/data-exchange/export-xlsx.js',
        'plugins/data-exchange/parse-table.js',
        'plugins/recaptcha/index.js',
        'plugins/recaptcha/middleware.js',
        'plugins/recaptcha/verify.js',
        'plugins/audit-log/migration-template.js',
        'plugins/audit-log/api-handlers.js',
        'plugins/audit-log/index.js',
        'plugins/audit-log/middleware.js',
        'plugins/site-analytics/client-error-handler.js',
        'plugins/site-analytics/api-handlers.js',
        'plugins/dashboard/index.js',
        'plugins/orm-cache-admin/api-handlers.js',
        'plugins/rate-limit/index.js',
        'plugins/upload/index.js',
        'plugins/upload/local-file-provider.js',
        'plugins/rest-resources/index.js',
        'plugins/redirect/index.js',
        'core/orm/migrations/scaffold.js',
        'core/orm/seeder.js',
        'src/client-runtime/bootstrap-*.js',
        'core/orm/types.js',
        'core/orm/cache/types.js',
      ],
      thresholds: {
        lines: 90,
        statements: 90,
        branches: 90,
        functions: 90,
      },
    },
  },
});
