'use strict';

const { DEFAULT_FIELDS } = require('./config');

/**
 * Generate idempotent Knex migration for Polar billing columns.
 * @param {Object} [opts]
 * @param {string} [opts.tableName='users']
 * @param {Object} [opts.fields]
 */
function generatePolarMigration(opts = {}) {
  const tableName = opts.tableName || 'users';
  const f = { ...DEFAULT_FIELDS, ...(opts.fields || {}) };

  return `/**
 * Migration: Add Polar.sh billing fields to ${tableName}
 * Auto-generated by polar plugin — idempotent (safe to re-run)
 */

exports.up = async function up(knex) {
  const hasTable = await knex.schema.hasTable('${tableName}');
  if (!hasTable) return;

  const hasTier = await knex.schema.hasColumn('${tableName}', '${f.tier}');
  if (!hasTier) {
    await knex.schema.alterTable('${tableName}', (table) => {
      table.string('${f.tier}', 32).notNullable().defaultTo('free').index();
      table.string('${f.polarCustomerId}', 128).nullable().index();
      table.string('${f.polarSubscriptionId}', 128).nullable().index();
      table.string('${f.polarStatus}', 32).notNullable().defaultTo('none').index();
      table.string('${f.polarCurrentPeriodEnd}', 64).nullable();
      table.boolean('${f.polarCancelAtPeriodEnd}').notNullable().defaultTo(false);
    });
  }
};

exports.down = async function down(knex) {
  const hasTable = await knex.schema.hasTable('${tableName}');
  if (!hasTable) return;

  const hasTier = await knex.schema.hasColumn('${tableName}', '${f.tier}');
  if (hasTier) {
    await knex.schema.alterTable('${tableName}', (table) => {
      table.dropColumn('${f.tier}');
      table.dropColumn('${f.polarCustomerId}');
      table.dropColumn('${f.polarSubscriptionId}');
      table.dropColumn('${f.polarStatus}');
      table.dropColumn('${f.polarCurrentPeriodEnd}');
      table.dropColumn('${f.polarCancelAtPeriodEnd}');
    });
  }
};
`;
}

module.exports = {
  generatePolarMigration,
};
