/**
 * Migration: Create admin_users table
 * Auto-generated by admin panel plugin
 */

exports.up = function(knex) {
  return knex.schema.createTable('admin_users', (table) => {
    table.bigIncrements('id').primary();
    table.string('email', 255).notNullable().unique();
    table.string('password', 255).notNullable();
    table.string('name', 255).notNullable();
    table.string('role', 50).defaultTo('admin');
    table.boolean('active').defaultTo(true);
    table.timestamp('created_at').defaultTo(knex.fn.now());
    table.timestamp('updated_at').defaultTo(knex.fn.now());
    
    table.index(['email']);
  });
};

exports.down = function(knex) {
  return knex.schema.dropTableIfExists('admin_users');
};
