/**
 * Node.js deployment adapter
 * @module adapters/node
 */

const { capabilityList } = require('../types');

const capabilities = {
  fetch: true,
  listen: true,
  fs: true,
  nativeModules: true,
};

module.exports = {
  name: 'node',
  version: '1.0.0',
  capabilities,

  /**
   * @param {import('../../core/build/types').WebspressoManifest} manifest
   */
  validate(manifest) {
    return { ok: true, errors: [], warnings: [] };
  },

  /**
   * @param {import('../../core/build/types').WebspressoManifest} _manifest
   */
  generateEntry(_manifest) {
    return `/**
 * Webspresso Node production entry — generated by webspresso build
 */
import { createAppFromManifest } from 'webspresso/build/runtime/create-app-from-manifest';
import manifest from './manifest.json' assert { type: 'json' };
import { handlers } from './handlers.mjs';

const { app } = createAppFromManifest({
  manifest,
  handlers,
  pagesDir: 'pages',
});

const port = Number(process.env.PORT || 3000);
app.listen(port, () => {
  console.log(\`Webspresso listening on http://localhost:\${port}\`);
});
`;
  },

  /**
   * @param {import('../../core/build/types').WebspressoManifest} _manifest
   * @param {string} outputDir
   */
  bundleOptions(_manifest, outputDir) {
    return {
      platform: 'node',
      format: 'esm',
      target: 'node18',
      external: [
        'better-sqlite3',
        'bcrypt',
        'sharp',
        'pg',
        'mysql2',
        'knex',
        'fsevents',
        'knex-cloudflare-d1',
      ],
      banner: { js: "import { createRequire } from 'module'; const require = createRequire(import.meta.url);" },
    };
  },
};

module.exports.capabilityNames = capabilityList(capabilities);
