/**
 * Cloudflare Workers deployment adapter
 * @module adapters/cloudflare
 */

const path = require('path');
const { capabilityList } = require('../types');

const capabilities = {
  fetch: true,
  listen: false,
  fs: false,
  nativeModules: false,
  d1: true,
  kv: true,
  r2: true,
  assets: true,
};

const NODE_ONLY = new Set(['admin-panel', 'adminPanelPlugin', 'upload', 'uploadPlugin', 'data-exchange']);

module.exports = {
  name: 'cloudflare',
  version: '1.0.0',
  capabilities,

  /**
   * @param {import('../../core/build/types').WebspressoManifest} manifest
   */
  validate(manifest) {
    /** @type {object[]} */
    const errors = [];
    /** @type {object[]} */
    const warnings = [];

    for (const p of manifest.plugins || []) {
      if (!p.edgeCompatible) {
        errors.push({
          code: 'WS_BUILD_PLUGIN_UNSUPPORTED',
          message: `Plugin "${p.name}" is not edge-compatible`,
          hint: 'Remove from config/app.js or deploy on Node adapter.',
        });
      }
    }

    if (manifest.middleware?.session?.store === 'memory') {
      errors.push({
        code: 'WS_BUILD_SESSION_MEMORY',
        message: 'In-memory sessions are not supported on Cloudflare Workers',
        hint: 'Use KV/D1 session store or cookie-only JWT.',
      });
    }

    return { ok: errors.length === 0, errors, warnings };
  },

  /**
   * @param {import('../../core/build/types').WebspressoManifest} _manifest
   * @param {{ cwd?: string }} [ctx]
   */
  generateEntry(_manifest, ctx) {
    const appRoot = ctx?.cwd || process.cwd();
    const modulePaths = [path.join(appRoot, 'node_modules'), appRoot];
    return `/**
 * Webspresso Cloudflare Worker entry — generated by webspresso build
 */
import knex from 'knex';
import d1Base from 'knex-cloudflare-d1';
import createD1KnexClient from 'webspresso/core/orm/d1-knex-client.js';
import { createAppFromManifest } from 'webspresso/build/runtime/create-app-from-manifest';
const d1Client = createD1KnexClient(d1Base);
import manifest from './manifest.json' assert { type: 'json' };
import { handlers } from './handlers.mjs';
import precompiledTemplates from './templates.mjs';

const modulePaths = ${JSON.stringify(modulePaths)};

/** @type {{ app: import('webspresso').WebspressoCompatApp } | null} */
let cached = null;

function getApp(env) {
  if (!cached) {
    cached = createAppFromManifest({
      manifest,
      handlers,
      pagesDir: 'pages',
      bindings: env,
      modulePaths,
      dbRuntime: { knex, d1Client },
      precompiledTemplates,
      clientRuntime: { alpine: false, swup: false },
      logging: false,
    });
  }
  return cached.app;
}

export default {
  fetch(request, env, ctx) {
    return getApp(env).fetch(request, env, ctx);
  },
};
`;
  },

  /**
   * @param {import('../../core/build/types').WebspressoManifest} _manifest
   * @param {string} _outputDir
   */
  bundleOptions(_manifest, _outputDir) {
    return {
      platform: 'node',
      format: 'esm',
      target: 'es2022',
      conditions: ['worker', 'import', 'require'],
      mainFields: ['module', 'main'],
      define: {
        'process.env.NODE_ENV': '"production"',
      },
      external: [
        'bcrypt',
        'better-sqlite3',
        'sharp',
        'mysql2',
        'pg',
        'knex',
        'sqlite3',
        'mysql',
        'tedious',
        'oracledb',
        'fsevents',
        'chokidar',
      ],
    };
  },
};

module.exports.capabilityNames = capabilityList(capabilities);
