name = "webspresso-app"
main = ".webspresso/worker/index.mjs"
compatibility_date = "2024-11-01"

[assets]
directory = ".webspresso/worker/assets/public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "webspresso"
migrations_dir = "migrations"

[vars]
NODE_ENV = "production"
